accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns=[
    path('products', views.products, name='products'),
    path('<int:pk>', views.customers, name='customer'),
    path('<int:pk>/order', views.order, name='order'),
    path('update/<pk><int:c_pk>', views.update_order, name='update'),
    path('delete/<pk><int:c_pk>', views.delete_order, name='delete'),
    path('profile', views.profile, name='user'),
    path('edit', views.account_setting, name='edit'),
    path('update/<pk>', views.updateCustomer, name='update_c')

    ]

cms/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('account/', include('accounts.urls')),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('login',views.user_login, name='login'),
    path('logout',views.user_logout, name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='reset_password'),
    path('password-sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('confirm-password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-changed/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.text import slugify 
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, blank=False)
    Phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    registered = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    profile_pic = models.ImageField(default="signup.png",null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) 
        super().save(*args, **kwargs) # Call the real save() method    


class Tag(models.Model):
    name = models.CharField(max_length=200, blank=False)

class Product(models.Model):
    name = models.CharField(max_length=200, blank=False)
    Category = models.CharField(max_length=200)
    Price = models.FloatField(max_length=200)
    Description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    tag = models.ForeignKey(Tag, related_name='tags',on_delete=models.SET_NULL,null=True, blank=True)

    def __str__(self):
        return self.name
       

class Order(models.Model):

    STATUS = (
        ('Pending', 'Pending'),
        ('Out For Delivery', 'Out For Delivery'),
        ('Delivered', 'Delivered')
    )
    customer = models.ForeignKey(Customer, related_name='orders',on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product,related_name='orders', on_delete=models.SET_NULL,null=True)
    status = models.CharField(max_length=200, choices=STATUS)
    date_ordered = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

accounts/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'  
        exclude = ['user','slug']

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'  

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']  
        widgets={
            'username':forms.TextInput(attrs={'class':'form__input','placeholder':'Username'}),
            'email':forms.EmailInput(attrs={'class':'form__input','placeholder':'Email','id':'email'}),
             }


class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['date_created']
      

accounts/views.py
from django.shortcuts import render, redirect
from .models import *
from . import forms
from django.forms import inlineformset_factory
from .filters import OrderFilter
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.contrib.auth.models import User


# Create your views here.
@login_required(login_url='login')
@allowed_users(allowed_roles=['Staff'])
def products(request):
    form = forms.ProductForm
    products = Product.objects.all()
    context = {
        'products':products,
        'form': form
    }
    if request.method == 'POST':
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:products')
        else:
            form = forms.ProductForm    
    return render(request, 'accounts/products.html',context)





@login_required(login_url='login')
@allowed_users(allowed_roles=['Customer'])
def profile(request):
    orders = request.user.customer.orders.all()
    orders_c = orders.filter(status='Delivered').count()
    orders_p = orders.filter(status='Pending').count()
    total_o = orders.count()
    context={
        'orders':orders,
        'total_o': total_o,
        'delivered': orders_c,
        'pending': orders_p
        }
    return render(request, 'accounts/profile.html', context)

@login_required(login_url='login')
@admin_only
def updateCustomer(request,pk):
    customer= Customer.objects.get(id=pk)
    form = forms.CustomerForm(instance=customer)
    if request.method == 'POST':
        form = forms.CustomerForm(request.POST, instance=customer) 
        if form.is_valid():
            form.save()
            return redirect('accounts:customer',pk=pk)
        else:
            form = forms.CustomerForm(instance=customer)
    context = {
        'form':form,
        'customer': customer
    }        
    return render(request, 'accounts/update_customer.html', context)    

@login_required(login_url='login')
@allowed_users(allowed_roles=['Customer'])
def account_setting(request):
    user = request.user.customer
    form = forms.CustomerForm(instance=user)
    if request.method == 'POST':
        form = forms.CustomerForm(request.POST,request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('accounts:edit')

    context={
        'form':form
    }
    return render(request, 'accounts/edit.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['Staff'])
def customers(request,pk):
    customer = Customer.objects.get(id=pk)
    orders = customer.orders.all()
    myfilter = OrderFilter(request.GET, queryset=orders)
    orders = myfilter.qs
    context = {
        'customer':customer,
        'orders': orders,
        'myfilter': myfilter,
        'customer_o': orders.count()
    }
    return render(request, 'accounts/customer.html', context)  



@login_required(login_url='login')
@allowed_users(allowed_roles=['Staff'])
def order(request,pk):
    order_formset = inlineformset_factory(Customer,Order, fields=('product','status'), extra=7)
    customer = Customer.objects.get(pk=pk)
    formset = order_formset(instance=customer)
    #form = forms.OrderForm() 
    if request.method == 'POST':
        #form = forms.OrderForm(request.POST)
        formset = order_formset(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('home') 
        else:
            formset = order_formset(instance=customer)        
    context = {
        'formset':formset
    }
    return render(request, 'accounts/order_form.html', context)      


@login_required(login_url='login')
@allowed_users(allowed_roles=['Staff'])
def update_order(request,pk,c_pk):
    order = Order.objects.get(pk=pk)
    form = forms.OrderForm(instance=order)
    if request.method == 'POST':
        form = forms.OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('accounts:customer',pk=c_pk) 
        else:
            form = forms.OrderForm(instance=order)           
    context = {
        'form':form
    }
    return render(request, 'accounts/update_order.html', context)     


@login_required(login_url='login')
@allowed_users(allowed_roles=['Staff'])
def delete_order(request, pk):
    order = Order.objects.get(pk=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('') 
    context = {
        'item': order
    }    
    return render(request, 'accounts/delete_order.html', context)

accounts/templates/accounts/Edit.html
    {% extends "cms/base.html" %}
    {%load static %}
    {% block content %}
      
   <head>
       <link rel="stylesheet" href="{%static '/css/master.css' %}">
   </head>
   <br>
   <br>
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<div class="profile-usertitle">
					<div class="profile-userpic">
                        <img src="{{request.user.customer.profile_pic.url}}" class="img-responsive" alt="">
                    </div>
					<div class="profile-usertitle-name">
						{{request.user}}
					</div>
					<div class="profile-usertitle-job">
						Customer
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">View Orders</button>
                </div>
            </div>
            </div>
            <div class="col-md-9">
                <div class="profile-content">
                   <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" class="btn-danger btn" value="Update">
                    </form>
                </div>
            </div>
            </div>
            {% endblock %}

accounts/templates/accounts/customer.html
{% extends "cms/base.html" %}
{%block content %}
<div class="row" style="margin-top: 30px;">
    <div class="col md">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title">Customer</h5>
              <p>{{customer.name}}</p>
              <a class="btn btn-primary btn-sm" href="{%url 'accounts:update_c' customer.pk %}" class="card-link">Update Customer</a>
              <a class="btn btn-primary btn-sm" href="{% url 'accounts:order' customer.pk %}" class="card-link">Order</a>
            </div>
          </div>        
    </div>
    <div class="col md">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title">Contact Information</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{customer.email}}</h6>
              <h6 class="card-subtitle mb-2 text-muted">{{customer.phone}}</h6>
            </div>
          </div>        
    </div>
    <div class="col md">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title">Total Orders</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{customer_o}}</h6>
            </div>
          </div>        
    </div>
</div>
<br>
<div class="card card-body">
  <h6 class="card-subtitle mb-2 text-muted">Search</h6>
  <form method="GET">
      {{myfilter.form}}
      <input type="submit" value="Filter" class="btn btn-primary">
  </form>
</div>
<div class="col md">  
  <br>
  <br>
  <hr>
  <h6 class="card-subtitle mb-2 text-muted">Orders</h6>
    
        <div class="card card-body">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Category</th>
                <th scope="col">Ordered On</th>
                <th scope="col">Status</th>
                <th scope="col">Update</th>
                <th scope="col">Remove</th>
              </tr>
            </thead>  
            <tbody>
              {%for order in orders %}
              <tr>
                <td>{{order.product}}</td>
                <td>{{order.category}}</td>
                <td>{{order.date_ordered}}</td>
                <td>{{order.status}}</td>
                <td><a href="{%url 'accounts:update' pk=order.pk c_pk=customer.pk%}" class="btn btn-success btn-sm">Update</a></td>
                <td><a href="{%url 'accounts:delete' pk=order.pk c_pk=customer.pk%}" class="btn btn-danger btn-sm">Remove</a></td>
              </tr>
              {%endfor%}
            </tbody>         
          </table>
      </div> 
</div> 
{%endblock%}

accounts/templates/accounts/dashboard.html
{%extends 'cms/base.html' %}
{%block content%}

{% include 'accounts/status.html' %}

<hr>
<div class="row">
    <div class="col md-3">
        <h5>Customers</h5>
        <hr>
        <div class="card card-body">
            <a href="#" class="btn btn-primary">Create Customer</a>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Customers</th>
                    <th scope="col">Info</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {%for customer in customers %}
                  <tr>
                    <td>
                      {{customer.name}}
                    </td>
                    <td>
                      {{customer.email}}
                    </td>
                    <td><a href="{% url 'accounts:customer' pk=customer.pk %}">View</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

 <div class="col md-9">  
    <h5>Recent Orders</h5>
    <hr>
        <div class="card card-body">
          <a href="#" class="btn btn-primary">View all Orders</a>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Ordered On</th>
                <th scope="col">Status</th>
                <th scope="col">Update</th>
                <th scope="col">Remove</th>
              </tr>
            </thead>  
            <tbody>
              {%for order in orders %}
              <tr>
                <td>{{order.product}}</td>
                <td>{{order.date_ordered}}</td>
                <td>{{order.status}}</td>
                <td><a href="{%url 'accounts:update' pk=order.pk c_pk=order.customer.pk %}" class="btn btn-success btn-sm">Update</a></td>
                <td><a href="{%url 'accounts:delete' pk=order.pk c_pk=order.customer.pk %}" class="btn btn-danger btn-sm">Remove</a></td>
              </tr>
              {%endfor%}
            </tbody>         
          </table>
      </div> 
</div> 
</div>
{%endblock%}

accounts/templates/accounts/delete_order.html
{% extends "cms/base.html" %}

<h6>Do you want to delete {{item}}</h6>
<form method="POST" action="{% url 'account:delete' slug={{item}}">
    {% csrf_token %}
    <button class="btm" type="submit">Delete</button>
</form>

accounts/templates/accounts/login.html
{%load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>Login</title>
</head>

<body>
	<div class="user">
		<header class="user__header">
			<img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3219/logo.svg" alt="" />
			<h1 class="user__title">LOGIN</h1>
		</header>

		<form class="form" method="POST">
			{% csrf_token %}
			{% if messages %}
			{%for message in messages %}
			<div class="error">
				{{ message }}
			</div>
			{%endfor%}
			{% endif %}
			<div class="form__group">
				<input type="text" placeholder="Username" class="form__input" name="username" />
			</div>

			<div class="form__group">
				<input type="password" placeholder="Password" class="form__input" name="password" />
			</div>

			<button class="btn" type="submit">Login</button>

		</form>
		<br>

		<div style="text-align: center; color: azure;">
			<p>No Account? &nbsp; &nbsp;<a href="{% url 'register' %}"
					style="text-decoration: none; color:coral;">Register</a></p>
			<br>
			<small><a href="{% url 'reset_password' %}" style="text-decoration: none; color:azure;">Forgot
					Password?</a></small>
		</div>
	</div>


	<script>
		const button = document.querySelector('.btn')
		const form = document.querySelector('.form')

		button.addEventListener('click', function () {
			form.classList.add('form--no')
		});
	</script>
</body>

</html>

accounts/templates/accounts/order_form.html
{% extends "cms/base.html" %}
{% block content %}
<br>
  <form method="post">
      {%csrf_token%}
      {{formset.management_form}}
      {%for form in formset %}
          {{form}}
          <hr>
      {%endfor%}
    <button type="submit" class="btn btn-primary">Order</button>
  </form>
{% endblock%}

accounts/templates/accounts/password_reset_complete.html
{% extends 'cms/base.html' %}
{% block content %}

<p> "Your password has been set.  You may go ahead and log in now." </p>

<p><a href="{% url 'login' %}">Log in</a></p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'cms/base.html' %}

{%block content%}

{% if validlink %}

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">New password:</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">Confirm password:</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="Change my password">
</fieldset>
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'cms/base.html' %}

{%block content%}

<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'cms/base.html' %}

{%block content%}
<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" class="btn btn-primary" value="Reset my password">
</form>
{%endblock%}

accounts/templates/accounts/products.html
{% extends 'cms/base.html' %}
{%block content %}
<div class="col md-7"> 
  <br> 
    <h5>Products</h5>
    <hr>
    <br>
    <form method="POST">
      {% csrf_token %}
      {%if form.errors %}
			<div class="error">
				{% for field in form %}
					{% if field.help_text %}<dd><p></p></dd>{% endif %}
					{% if field.errors %}<dd class="errors">{{ field.errors }}</dd>{% endif %}
				{% endfor %}
			</div>
			{%endif%}
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="id_name">Name:</label>
          <input type="text" class="form-control" name="name" maxlength="200" required id="inputEmail4">
        </div>
        <div class="form-group col-md-6">
          <label for="id_Category">Category:</label> 
          <input type="text" class="form-control" name="Category" maxlength="200" required id="id_Category">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="id_Price">Price:</label> 
          <input type="number" class="form-control" name="Price" step="any" required id="id_Price">  
        </div>
        <div class="form-group col-md-5">
          <label for="id_tag">Tag</label>
          <select name="tag" id="tag" class="form-control">
            <option value selected>Choose...</option>
          </select>
        </div>
      </div>
      <div class="form-group">
        <label for="id_description">Description</label>
        <input type="text" name="Description"
        class="form-control" id="id_Description" placeholder="Description">
      </div>
      <button type="submit" class="btn btn-primary">Create Product</button>
    </form>
    <br>
        <div class="card card-body">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Category</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
            {%for product in products %}
            <tr>
                <td>
                    {{product.name}}
                </td>
                <td>
                    {{product.Category}}
                </td>
                <td>
                    {{product.Price}}
                </td>
            </tr> 
            {%endfor%}  
            </tbody>        
          </table>
      </div> 
</div> 
{%endblock%}

accounts/templates/accounts/profile.html
{% extends 'cms/base.html' %}
{%block content %}
<hr>
<div class="card text-white bg-info mb-3">
    <h5 class="card-header">Dashboard</h5>
</div>
  
<div class="row">
    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Total Orders</h5>
            <div class="card-body">
              <h3 class="card-text">{{total_o}}</h3>      
            </div>
          </div>
    </div>


    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Orders Completed</h5>
            <div class="card-body">
              <h3 class="card-text">{{delivered}}</h3>      
            </div>
          </div>
    </div>



    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Orders Pending</h5>
            <div class="card-body">
              <h3 class="card-text">{{pending}}</h3>             
            </div>
          </div>
    </div>
</div>
<br>
<div class="col md-7">  
  <h5>Orders</h5>
  <hr>
      <div class="card card-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Product</th>
              <th scope="col">Ordered On</th>
              <th scope="col">Status</th>
            </tr>
          </thead>  
          <tbody>
            {%for order in orders %}
            <tr>
              <td>{{order.product}}</td>
              <td>{{order.date_ordered}}</td>
              <td>{{order.status}}</td>
            </tr>
            {%endfor%}
          </tbody>         
        </table>
    </div> 
</div> 
</div>
{%endblock%}

accounts/templates/accounts/status.html
<hr>
<div class="row">
    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Total Orders</h5>
            <div class="card-body">
              <h3 class="card-text">{{total_o}}</h3>      
            </div>
          </div>
    </div>


    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Orders Completed</h5>
            <div class="card-body">
              <h3 class="card-text">{{delivered}}</h3>      
            </div>
          </div>
    </div>



    <div class="col">
        <div class="card text-white bg-info mb-3">
            <h5 class="card-header">Orders Pending</h5>
            <div class="card-body">
              <h3 class="card-text">{{pending}}</h3>             
            </div>
          </div>
    </div>
</div>

accounts/templates/accounts/update_order.html
{% extends "cms/base.html" %}
{% block content %}
<br>
  <form method="post">
      {%csrf_token%}
          {{form}}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
{% endblock%}