accounts/urls.py
from django.urls import path
from . import views


app_name='accounts'

urlpatterns=[
    path('products', views.products, name='products'),
    path('<int:pk>', views.customers, name='customer'),
    path('<int:pk>/order', views.order, name='order'),
    path('update/<pk><int:c_pk>', views.update_order, name='update'),
    path('delete/<pk><int:c_pk>', views.delete_order, name='delete'),
    path('profile', views.profile, name='user'),
    path('edit', views.account_setting, name='edit'),
    path('update/<pk>', views.updateCustomer, name='update_c')

    ]

cms/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('account/', include('accounts.urls')),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('login',views.user_login, name='login'),
    path('logout',views.user_logout, name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='reset_password'),
    path('password-sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('confirm-password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-changed/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/views.py
from django.shortcuts import render,redirect
from accounts.models import *
from accounts import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.decorators import *
from django.contrib.auth.models import Group


@login_required(login_url='login')
@admin_only
def home(request):
    orders = Order.objects.all()
    orders_c = Order.objects.all().order_by('-date_ordered')[:3]
    products = Product.objects.all()
    customers = Customer.objects.all()

    total_orders = orders.count()
    total_customers = customers.count()
    delivered = orders.filter(status='Delivered').count()
    pending = orders.filter(status='Pending').count()


    context = {
        'orders': orders_c,
        'products': products,
        'customers': customers,
        'total_o': total_orders,
        'total_c': total_customers,
        'pending': pending,
        'delivered': delivered,
    }
    return render(request,'accounts/dashboard.html', context)





@unauthenticated_user
def register(request):
        form =  forms.UserForm()
        if request.method == 'POST':
            form = forms.UserForm(request.POST)
            if form.is_valid():          
                user = form.save()
                return redirect('home')
            
        context = {
            'form':form
        }
        return render(request,'accounts/register.html',context)

@unauthenticated_user
def user_login(request):   
        form = forms.UserForm
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request,"Username or Password is Incorrect")  
        context = {'form':form}
        return render(request,'accounts/login.html',context)

@login_required(login_url='login')
def user_logout(request):
    logout(request)
    return redirect('login')    

templates/cms/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Decumy- Customer management application </title>
  </head>
  <body>
    {% include 'cms/navbar.html' %}

    <div class="container">
      {% block content %}
      
      {% endblock  %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/cms/navbar.html
<style>
  .user{
    color: #ffffff;
    font-size: 17px;
  }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}" style="color: turquoise;">Decux</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      {%if request.user.is_staff %}
      <div class="navbar-nav justify-content-end">
        <a class="nav-item nav-link active" href="{% url 'home' %}">Dashboard<span class="sr-only"></span></a>
        <a class="nav-item nav-link" href="{% url 'accounts:products' %}">Products</a>
        <a class="nav-item nav-link" href="#">Orders</a>
       </div>
       {%endif%}
    </div>
    {%if user.is_authenticated %}
    <span class="user">Welcome, &nbsp;<a style="text-decoration: none; color: tomato;"href="{% url 'accounts:edit' %}">{{ request.user}}</a></span> 
    <a class="user nav-item nav-link" href="{%url 'logout' %}">Logout</a>
    {%endif%}
  </nav>